services:
  - type: web
    name: django-backend
    env: python
    pythonVersion: 3.12.3
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn ProjectAsh.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ProjectAsh.settings
      - key: SECRET_KEY
        value: "REPLACE_WITH_SECRET_OR_SET_ON_RENDER"
      - key: DATABASE_URL
        fromDatabase:
          name: your-db-name
          property: connectionString
